(load "config/local/whitespace")
(load "config/local/yesno")
(load "config/local/autofill")
(load "config/local/clipboard")
(load "config/local/rst")
(load "config/local/font")
(load "config/local/po")
(when (eq window-system 'ns)
  (load "config/local/osx"))
(load "config/local/atomic-chrome")
(load "config/local/indent")
;;(load "config/local/origami")
(load "config/local/yafolding")
